// This manifest lists all images in images/guitars/ for the gallery. Add new filenames here to auto-load them.
// This file is auto-generated or can be updated manually as needed.
window.GUITAR_IMAGES = [
  "images/guitars/scimitar1.jpg",
  "images/guitars/scimitar1.mp4",
  "images/guitars/scimitar2.jpg",
  "images/guitars/scimitar2.mp4",
  "images/guitars/scimitar3.jpg",
  "images/guitars/scimitar4.jpg",
  "images/guitars/scimitar5.jpg",
  "images/guitars/scimitar6.jpg",
  "images/guitars/scimitar7.jpg",
  "images/guitars/scimitar8.jpg",
  "images/guitars/scimitar9.jpg",
  "images/guitars/scimitar10.jpg",
  "images/guitars/scimitar11.jpg",
  "images/guitars/scimitar12.jpg",
  "images/guitars/scimitar13.jpg",
  "images/guitars/scimitar14.jpg",
  "images/guitars/scimitar15.jpg",
  "images/guitars/scimitar16.jpg",
  "images/guitars/scimitar17.jpg",
  "images/guitars/scimitar18.jpg",
  "images/guitars/scimitar19.jpg",
  "images/guitars/scimitar20.jpg",
  "images/guitars/scimitar21.jpg",
  "images/guitars/scimitar22.jpg",
  "images/guitars/scimitar23.jpg",
  "images/guitars/scimitar24.jpg"
];
